### PR TITLE
Fix massive p0s

### PR DESCRIPTION
**Pull request by LinkossLink**
Fix

### CODE REVIEW

**Comment by AakashSharma7269** [comment]
wow did you run like a global substitution ?
that's some serious dedication

**Comment by LinkossLink** [comment]
Fix pls

**Comment by AakashSharma7269** [comment]
This looks like a ill-formed PR
All the contributors here at linkass™️ corporation like to maintain code quality, please fix ty

**Comment by chweesee** [comment]
KEKW

**Comment by AakashSharma7269** [comment]
🤣

**Comment by AakashSharma7269** [comment]
mm possible bug, i'll look into this. Ty

**Comment by chweesee** [comment]
too minor

**Comment by AakashSharma7269** [comment]
mm @chweesee maybe fixed in a further update / branch although too minor

**Comment by chweesee** [comment]
closing as wontfix for now, might reopen if not sus

**Pull request closed without merging**
